// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusMsg {
    /// just wrapper message for enum type data
    #[prost(enumeration = "Status", tag = "1")]
    pub err_status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Device {
    /// device name (e.g. 'rbln0')
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// device id (e.g. '1120', '1121')
    #[prost(string, tag = "2")]
    pub dev_id: ::prost::alloc::string::String,
    /// device uuid (00000000-0000-0000-0000-000000000000 format)
    #[prost(string, tag = "3")]
    pub uuid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClockInfo {
    /// CP clock information (Mhz)
    #[prost(int32, tag = "1")]
    pub cp_clock: i32,
    /// DNC1 clock information (Mhz)
    #[prost(int32, tag = "2")]
    pub dc1_clock: i32,
    /// DNC2 clock information (Mhz)
    #[prost(int32, tag = "3")]
    pub dc2_clock: i32,
    /// Bus clock information (Mhz)
    #[prost(int32, tag = "4")]
    pub bus_clock: i32,
    /// SHM clock information (Mhz)
    #[prost(int32, tag = "5")]
    pub shm_clock: i32,
    /// error status
    #[prost(enumeration = "Status", tag = "6")]
    pub err_status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionInfo {
    /// Firmware version.
    #[prost(string, tag = "1")]
    pub fw_version: ::prost::alloc::string::String,
    /// Kernel driver version.
    #[prost(string, tag = "2")]
    pub drv_version: ::prost::alloc::string::String,
    /// SMC version.
    #[prost(string, tag = "3")]
    pub smc_version: ::prost::alloc::string::String,
    /// error status
    #[prost(enumeration = "Status", tag = "4")]
    pub err_status: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HwInfo {
    /// temperature in celsius unit.
    #[prost(float, tag = "1")]
    pub temperature: f32,
    /// hardware watt.
    #[prost(float, tag = "2")]
    pub watt: f32,
    /// error status
    #[prost(enumeration = "Status", tag = "3")]
    pub err_status: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemoryInfo {
    /// device total memory (GB unit)
    #[prost(float, tag = "1")]
    pub total_mem: f32,
    /// device memory in use (GB unit)
    #[prost(float, tag = "2")]
    pub used_mem: f32,
    /// error status
    #[prost(enumeration = "Status", tag = "3")]
    pub err_status: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UtilInfo {
    /// utilization(percent) of device processing unit
    #[prost(float, tag = "1")]
    pub utilization: f32,
    /// error status
    #[prost(enumeration = "Status", tag = "2")]
    pub err_status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventInfo {
    /// device name
    #[prost(string, tag = "1")]
    pub dev_name: ::prost::alloc::string::String,
    /// event type
    #[prost(enumeration = "EventType", tag = "2")]
    pub event_type: i32,
    /// event value
    #[prost(enumeration = "EventSource", tag = "3")]
    pub value: i32,
    /// sub event value
    #[prost(int32, tag = "4")]
    pub sub_value: i32,
    /// event trigger time (uptime)
    #[prost(double, tag = "5")]
    pub kernel_time: f64,
    /// UTC time with host time zone.
    #[prost(string, tag = "6")]
    pub utc_time: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    /// device name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// device uuid
    #[prost(string, tag = "2")]
    pub uuid: ::prost::alloc::string::String,
    /// device total memory (GB unit)
    #[prost(float, tag = "3")]
    pub total_mem: f32,
    /// device memory in use (GB unit)
    #[prost(float, tag = "4")]
    pub used_mem: f32,
    /// temperature in celsius unit.
    #[prost(float, tag = "5")]
    pub temperature: f32,
    /// hardware watt currently consumed
    #[prost(float, tag = "6")]
    pub watt: f32,
    /// firmware version
    #[prost(string, tag = "7")]
    pub fw_version: ::prost::alloc::string::String,
    /// kernel driver version
    #[prost(string, tag = "8")]
    pub drv_version: ::prost::alloc::string::String,
    /// device utilization
    #[prost(float, tag = "9")]
    pub utilization: f32,
    /// error status
    #[prost(enumeration = "Status", tag = "10")]
    pub err_status: i32,
}
/// Just wrapper message to indicates dummy!
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    /// indicates valid data in message
    Succeed = 0,
    /// indicates invalid data in message
    Failed = 1,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Succeed => "SUCCEED",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCEED" => Some(Self::Succeed),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    /// event does snot require response(daemon to kernel response)
    NoResponse = 0,
    /// event requires response(daemon to kernel response)
    ResponseRequired = 1,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoResponse => "NO_RESPONSE",
            Self::ResponseRequired => "RESPONSE_REQUIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NO_RESPONSE" => Some(Self::NoResponse),
            "RESPONSE_REQUIRED" => Some(Self::ResponseRequired),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventSource {
    /// event occured from single device hard reset
    SignleHardReset = 0,
    /// event occured from rsd device hard reset
    RsdHardReset = 1,
    /// event occured from TDR
    TdrEvent = 2,
    /// event occured from CP event
    CpEvent = 3,
}
impl EventSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SignleHardReset => "SIGNLE_HARD_RESET",
            Self::RsdHardReset => "RSD_HARD_RESET",
            Self::TdrEvent => "TDR_EVENT",
            Self::CpEvent => "CP_EVENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIGNLE_HARD_RESET" => Some(Self::SignleHardReset),
            "RSD_HARD_RESET" => Some(Self::RsdHardReset),
            "TDR_EVENT" => Some(Self::TdrEvent),
            "CP_EVENT" => Some(Self::CpEvent),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod rbln_services_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// RBLN API Services
    #[derive(Debug, Clone)]
    pub struct RblnServicesClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RblnServicesClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RblnServicesClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RblnServicesClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RblnServicesClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// search device list with device name (e.g. 'rbln0')
        pub async fn get_device_list(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Device>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getDeviceList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getDeviceList"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// search device list with device name (e.g. 'rbln0')
        pub async fn get_serviceable_device_list(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Device>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getServiceableDeviceList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "rblnservices.RBLNServices",
                        "getServiceableDeviceList",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// reset device from device name specified.
        pub async fn reset_device(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::StatusMsg>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/resetDevice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "resetDevice"));
            self.inner.unary(req, path, codec).await
        }
        /// reset all device in system. it is equivalent with rsd reset.
        pub async fn reset_all_device(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::StatusMsg>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/resetAllDevice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "resetAllDevice"));
            self.inner.unary(req, path, codec).await
        }
        /// get version about firmware, smc and kernel.
        pub async fn get_version(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::VersionInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getVersion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getVersion"));
            self.inner.unary(req, path, codec).await
        }
        /// get hardware temperature and watt in device.
        pub async fn get_hw_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::HwInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getHWInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getHWInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// get device equipped ram size and memory size in use.
        pub async fn get_memory_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::MemoryInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getMemoryInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getMemoryInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// get device clock information.
        pub async fn get_clock_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::ClockInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getClockInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getClockInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// get hardware event generated and reported by kernel driver.
        pub async fn get_event_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::EventInfo>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getEventInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getEventInfo"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// get total device info. for specified device.
        /// it includes device temperature, version, watt, memory info., clock info for specified device.
        pub async fn get_total_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DeviceInfo>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getTotalInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getTotalInfo"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// get utilization of NPU device
        pub async fn get_utilization(
            &mut self,
            request: impl tonic::IntoRequest<super::Device>,
        ) -> std::result::Result<tonic::Response<super::UtilInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rblnservices.RBLNServices/getUtilization",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rblnservices.RBLNServices", "getUtilization"));
            self.inner.unary(req, path, codec).await
        }
    }
}
